Feed View  UI
SwiftBuddiesTR/BuddiesIOS pull request #15
Opened 2024-04-10 17:45 UTC by KateKashko

2024-04-11 20:03 UTC, darkbringer1 requested changes

2024-04-11 20:03 UTC, darkbringer1 commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +//                            .foregroundColor(.mainGray)
Yorum kalmış silebilirsin

2024-04-11 20:03 UTC, darkbringer1 commented on Targets/SwiftBuddiesFeed/Sources/FeedView.swift
> +                }
Tüm view'ı buraya yazmaktansa başka bir feed list view oluşturup tek satırda çağırabiliriz

2024-04-11 20:03 UTC, darkbringer1 commented on Targets/SwiftBuddiesFeed/Sources/User.swift
> +struct User: Identifiable, Hashable, Codable{
Model ismini çok generic olmayacak şekilde yazabilirsin. UserModel yada UserResponseModel gibi

2024-04-11 20:03 UTC, darkbringer1 commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +// MARK: - action buttons
Butonlar ayrı component olabilir

2024-04-11 20:03 UTC, darkbringer1 commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +     // MARK: - image + username + date
Bu kısım ayrı bir component olabilir

2024-04-11 20:03 UTC, darkbringer1 commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +// MARK: - post content, location
Component

2024-04-11 20:03 UTC, darkbringer1 commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +// MARK: - like and comments counters
Aynı şekilde component olabilir

2024-04-15 10:41 UTC, KateKashko commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +//                            .foregroundColor(.mainGray)
done

2024-04-15 10:41 UTC, KateKashko commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +// MARK: - action buttons
done

2024-04-15 10:42 UTC, KateKashko commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +     // MARK: - image + username + date
done

2024-04-15 10:42 UTC, KateKashko commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +// MARK: - post content, location
done

2024-04-15 10:42 UTC, KateKashko commented on Targets/SwiftBuddiesFeed/Sources/FeedCell.swift
> +// MARK: - like and comments counters
done

2024-04-16 19:54 UTC, darkbringer1 commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostContentView.swift
> +                    }
```suggestion
 
```

bu kisim silinebilir

2024-04-16 20:02 UTC, darkbringer1 commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Components/ActionButton.swift
> +
```suggestion
  
    init(imageSystemName: String, label: String, isToggled: Bool, toggledColor: Color, action: @escaping () -> Void) {
        self.action = action
        self.imageSystemName = imageSystemName
        self.label = label
        self.isToggled = isToggled
        self.toggledColor = toggledColor
    }
```

completion/action olan yerlerde initializer yazmaya ozen gosterelim. Genel olarak initializer yazmak el aliskanligi olsun, aksi halde proje buyudugunde compiler'in kafasi karisabiliyor.

2024-04-16 20:03 UTC, darkbringer1 commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Components/ActionButton.swift
> +        Button(action: action) {
```suggestion
        Button {
          action?()
        } label: {
```

2024-04-16 20:03 UTC, darkbringer1 commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Components/ActionButton.swift
> +    let imageName: String
imageName yerine systemImageName kullanilmali, component icerisinde kullandigimizda hangi asseti verecegimizi bilmeliyiz

2024-04-16 20:04 UTC, darkbringer1 commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Model/Post.swift
> +    static var MOCK_POSTS: [Post] = [
isimlendirmelerde camelCase kullanirsak daha uyumlu olur

2024-04-16 20:05 UTC, darkbringer1 commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Model/User.swift
> +    static var MOCK_USERS: [User] = [
yukaridaki ayni durum, camelCase kullanilmali

2024-04-23 09:41 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Feed.swift
> +//
We can delete this file if we are not using.

2024-04-23 09:41 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Model/User.swift
> +struct User: Identifiable, Hashable, Codable{
```suggestion
struct User: Identifiable, Hashable, Codable {
```

2024-04-23 09:42 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPhotoButton.swift
> +        HStack{
```suggestion
        HStack {
```

2024-04-23 09:42 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPhotoButton.swift
> +            Button{
```suggestion
            Button {
```

2024-04-23 09:42 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPhotoButton.swift
> +                ZStack{
```suggestion
                ZStack {
```

2024-04-23 09:43 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostContentView.swift
> +        ScrollView{
```suggestion
        ScrollView {
```

2024-04-23 09:43 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostContentView.swift
> +            VStack{
```suggestion
            VStack {
```

2024-04-23 09:44 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostContentView.swift
> +
We can delete this empty line

2024-04-23 09:44 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostContentView.swift
> +
We can delete this empty line too 🙂

2024-04-23 09:44 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostHeaderButtonsView.swift
> +        HStack{
```suggestion
        HStack {
```

2024-04-23 09:44 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostHeaderButtonsView.swift
> +            Button{
```suggestion
            Button {
```

2024-04-23 09:45 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostHeaderButtonsView.swift
> +            Button{
```suggestion
            Button {
```

2024-04-23 09:45 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/View/AddPostView.swift
> +            VStack{
```suggestion
            VStack {
```

2024-04-23 09:46 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/ViewModel/AddPostViewModel.swift
> +class AddPostViewModel: ObservableObject{
```suggestion
final class AddPostViewModel: ObservableObject {
```

2024-04-23 09:46 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/Comments/CommentCell.swift
> +        HStack(spacing: 8){
```suggestion
        HStack(spacing: 8) {
```

2024-04-23 09:46 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/Comments/CommentCell.swift
> +            if let user = post.user{
```suggestion
            if let user = post.user {
```

2024-04-23 09:47 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/Comments/CommentCell.swift
> +                VStack(spacing: 8){
```suggestion
                VStack(spacing: 8) {
```

2024-04-23 09:47 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/Comments/CommentCell.swift
> +                    HStack(spacing: 8){
```suggestion
                    HStack(spacing: 8) {
```

2024-04-23 09:47 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/Comments/CommentView.swift
> +                ScrollView{
```suggestion
        NavigationStack {
            VStack {
                ScrollView {
```

2024-04-23 09:47 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/FeedCell.swift
> +        VStack{
```suggestion
    var body: some View {
        
        VStack {
```

2024-04-23 09:48 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/FeedCellCountersView.swift
> +        HStack{
```suggestion
        HStack {
```

2024-04-23 09:48 UTC, gokberkkoksoy commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/FeedCellHeaderView.swift
> +            if let user = post.user{
```suggestion
        HStack {
            if let user = post.user {
```

2024-05-06 11:38 UTC, KateKashko commented on Targets/SwiftBuddiesFeed/Sources/User.swift
> +struct User: Identifiable, Hashable, Codable{
Done

2024-05-06 11:45 UTC, KateKashko commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Model/Post.swift
> +    static var MOCK_POSTS: [Post] = [
Done

2024-05-06 11:47 UTC, KateKashko commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Model/User.swift
> +    static var MOCK_USERS: [User] = [
Done

2024-05-06 11:50 UTC, KateKashko commented on SwiftBuddiesIOS/Targets/FeedModule/Sources/Sources/AddPost/Components/AddPostContentView.swift
> +            VStack{
Anladım anladım) bboşluklar kontrol edicem

2025-02-05 07:15 UTC, merged