Login feature
SwiftBuddiesTR/BuddiesIOS pull request #21
Opened 2024-04-19 20:18 UTC by berkaytncl

### Issue Link :link:

### Goals :soccer:

**The primary goals of this pull request:**
1. Improve the login feature in the community app, working alongside Oğuzhan.
2. Use MVVM architecture and SwiftUI for development.
3. Add Firebase for various login options like email, anonymous, Apple, and Google login.

### Implementation Details :construction:

We've enhanced the login functionality of the community app, choosing MVVM for its organization and SwiftUI for its simplicity. Firebase integration adds versatile login methods, improving user experience and security.

### Testing Details :mag:

**TBD** 
### Screenshots/Gifs :camera:

```
<img src="" width="150">
```

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [x] Other... Please describe:

2024-04-22 20:34 UTC, canyoldas0 requested changes

2024-04-22 20:34 UTC, canyoldas0 commented on SwiftBuddiesIOS/Sources/TabFlowView.swift
> +            NavigationStack {
`NavigationStack` ProfileView'in icerisine koyulurs daha iyi olur

2024-04-22 20:34 UTC, canyoldas0 commented on SwiftBuddiesIOS/Targets/AuthModule/Sources/AuthenticationManager.swift
> +        let credential = GoogleAuthProvider.credential(withIDToken: tokens.idToken, accessToken: tokens.accessToken)
Google veya Apple `AuthProvider`'lara boyle erismek yerine `AuthenticationManager`'a bu servisler inject edilirse daha testable bir kod olur.

2024-04-22 20:34 UTC, canyoldas0 commented on SwiftBuddiesIOS/Sources/TabFlowView.swift
> +                ProfileView(showSignInView: $showSignInView)
Bu binding sadece sign in view'unu present etmek icin kullaniliyorsa boyle yapmaktansa NotificationCenter ile notification yollanabilir. Ki eninde sonunda boyle bir yapi baska ekranlar icin gerekebilir o yuzden `showSignInView` binding'ine gerek yok

2024-04-22 20:34 UTC, canyoldas0 commented on SwiftBuddiesIOS/Targets/LoginModule/Sources/AuthenticationViewModel.swift
> +        let _ = try await AuthenticationManager.shared.signInWithGoogle(tokens: tokens)
buradaki akista gerekli viewmodel sadece authentication manager'a erismeli ve o da inject edilmeli, buradaki token logic'inin viewmodel'in icerisinde olmasina gerek yok

2024-04-22 20:34 UTC, canyoldas0 commented on SwiftBuddiesIOS/Targets/LoginModule/Sources/AuthenticationViewModel.swift
> +        let _ = try await AuthenticationManager.shared.signInWithGoogle(tokens: tokens)
aynisi diger signIn metodlari icin de gecerli

2024-04-27 01:33 UTC, berkaytncl commented
gelistirmeyi tamamladim. conflictleri cozerken localization codegende sorun yasiyorum birlikte bakabilir miyiz? @canyoldas0

2024-04-30 18:47 UTC, darkbringer1 commented
> gelistirmeyi tamamladim. conflictleri cozerken localization codegende sorun yasiyorum birlikte bakabilir miyiz? @canyoldas0 

Dostum string cataloga modülde kullanılan yazıları ekledikten sonra scheme içinde localization codegen run edersen generated localized dosyası güncellenecektir

2024-04-30 18:59 UTC, darkbringer1 reviewed
Tamamını kontrol etmedim henüz, firebase projeden çıkartıldığında tekrar kontrol ederiz

2024-04-30 18:59 UTC, darkbringer1 commented on Project.swift
> +        .package(product: "FirebaseAuth", type: .runtime, condition: .none)
firebase projeden cikartir misiniz?

2024-04-30 18:59 UTC, darkbringer1 commented on SwiftBuddiesIOS/Resources/GoogleService-Info.plist
Bu dosya firebase çıkartılmasıyla uçacak

2024-04-30 19:17 UTC, darkbringer1 commented
https://github.com/SwiftBuddiesTR/BuddiesIOS/issues/20

Authentication akışının diyagramlarını çizer misiniz? Diyagramlar için https://youtu.be/VLPTNhW7R3Y?si=rtZRwMvhHyXaRq6Y bu video güzel bir açıklama yapmış. Bizim miro içine akışı çizebilirsiniz ♥️

2024-10-10 19:00 UTC, darkbringer1 approved these changes

2024-10-10 19:03 UTC, darkbringer1 approved these changes

2024-10-10 19:10 UTC, canyoldas0 approved these changes
👍

2024-10-10 19:13 UTC, merged